# This file configures the build at https://circleci.com/gh/ngrx/platform

# Opt-in to newer CircleCI system
# Complete documentation is at https://circleci.com/docs/2.0/
version: 2

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name`
# syntax dereferences it.
# See https://blog.daemonl.com/2016/02/yaml.html
# To validate changes, use an online parser, eg.
# https://yaml-online-parser.appspot.com/
var_1: &cache_key yarn-cache-{{ checksum "yarn.lock" }}
var_2: &run_in_ngcontainer
  docker:
    - image: angular/ngcontainer:0.3.3

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: yarn
      - run: yarn run build
      - run: yarn run build:stackblitz
      - save_cache:
          key: *cache_key
          paths:
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: dist-gh-pages
          paths:
            - projects/example-app/dist/*
            - stackblitz.html
  deploy:
    <<: *run_in_ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: yarn
      - attach_workspace:
          at: dist
      - run: yarn run deploy:gh-pages

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
